#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 19 07:30:04 2021

@author: m

Ch2 Example from page 130

Performs gaussian elimination on the system

Testing this example caught that my check for zeros on the diagonal was
implemented incorrectly and in the wrong place in the code.

"""

import numpy as np
from naf.linalg import gega, gesv

a = np.array([[0,2,0,1],
              [2,2,3,2],
              [4,-3,0,1],
              [6,1,-6,-5]], dtype=float)

b = np.array([0,-2,-7,6], dtype=float)

lu, ov = gega(a)

print(lu, ov)

print(gesv(lu, ov, b))